class AppString {
  static String title = 'Consectetur adipiscing elit.';
  static String para1 =
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla molestie nunc eget mauris aliquet efficitur. Proin molestie aliquam nulla, vitae porttitor mauris aliquam ut. Curabitur nisl justo, tempus vel dignissim sit amet, ultrices vel lacus. Integer eu nunc velit. Phasellus interdum, arcu et vestibulum placerat, orci neque faucibus massa, vehicula dignissim lectus quam in neque. Aenean augue massa, dictum a velit ut, venenatis ultrices metus. Nunc nec hendrerit quam, lobortis luctus lorem. Mauris sed urna sed augue tempor ultrices. Mauris gravida ante in dolor ultrices luctus. Nullam maximus et ipsum eu ultricies. Praesent nec laoreet orci, nec ornare odio. Sed euismod, ipsum non placerat consequat, ante enim dictum tellus, in congue nulla arcu at metus. Maecenas rutrum nunc non ligula pharetra iaculis. Nunc eu dapibus ipsum, vehicula commodo tellus. Praesent tincidunt turpis varius, fermentum libero sed, ultricies elit. Aenean volutpat, ligula in congue vehicula, ipsum tellus auctor tortor, ac hendrerit mauris dolor et mauris. Aliquam eget leo nulla. Aenean quis placerat mi. Integer quis imperdiet magna. Phasellus luctus elit ut risus gravida, nec semper eros mollis. Suspendisse congue faucibus enim, in sollicitudin mauris elementum vitae. Vestibulum id turpis nunc.';
  static String title2 = 'Sed id.';
  static String para2 =
      'Sed id quam id turpis semper facilisis laoreet interdum nunc. Pellentesque efficitur arcu id pharetra bibendum. Morbi quam purus, vehicula et sagittis eu, bibendum eu mi. Curabitur facilisis tellus libero, in aliquet erat fringilla vitae. Pellentesque vehicula venenatis gravida. Duis lacinia nec dolor nec imperdiet. Fusce sit amet risus lobortis odio vestibulum vehicula ac nec orci. Nullam ultrices, leo nec euismod interdum, risus mauris lobortis turpis, eget tristique purus diam vel felis. Curabitur fringilla, est et venenatis consequat, risus dui tempus felis, vel accumsan lectus elit ac orci. Aliquam dapibus nibh quis tortor faucibus, vehicula scelerisque augue scelerisque. Nunc non imperdiet dolor. Aenean tempus, quam eget rhoncus malesuada, lorem felis aliquam ex, nec tempor leo neque laoreet justo. In fringilla elit orci, sagittis blandit mi fermentum id. Nunc ac diam vel nulla pretium pellentesque quis eget orci. Sed ullamcorper semper auctor.';

  static String title3 = 'Written by ';
  static String title4 = 'NRK fitness ';
  static String title5 = 'on 13th Jan 2022';
}
